#ddev-generated
# Simple template to demonstrate laravel-nextjs
services:
  laravel-nextjs:
    container_name: ddev-${DDEV_SITENAME}-laravel-nextjs
    image: ${LARAVEL_NEXTJS_DOCKER_IMAGE:-busybox:stable}
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
