#!/bin/bash

## #ddev-generated
## Description: Run Laravel artisan commands
## Usage: artisan [command]
## Example: "ddev artisan migrate" or "ddev artisan make:model User"

cd /var/www/html/backend
php artisan "$@"
