#!/bin/bash

## #ddev-generated
## Description: Run npm commands in frontend directory
## Usage: npm-frontend [command]
## Example: "ddev npm-frontend install" or "ddev npm-frontend run build"

cd /var/www/html/frontend
npm "$@"
